### ISSUE TITLE
Need isLoading and Spinner to display Spinner while components are making HTTP Requests

### ISSUE THREAD

**Issue by ShinteiMai** [ShinteiMai/stronk#9]
contohnya misalnya pas register, itu kan makan waktu dulu, lebih bagus bikin state/hook yang namanya [isLoading, setIsLoading] terus kalau responsenya belom nyampe tampilin spinner aja. Itu tekniknya sama kayak yang di index.tsx  yang SplashScreen

**Comment by uriella** [comment]
maleman bang

**Comment by ShinteiMai** [comment]
unDerStanDaBle hAve a niCe DaY kawokawokawokawo
